/** 16x16 strings: space = empty, B body, A accent, E eye, M mouth, W white */
export type PixelKey = " " | "B" | "A" | "E" | "M" | "W" | "Z";

const idle = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEEBBEEBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBMMMMBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BB  BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const idle2 = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEEBBEEBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBMMBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BB  BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const eat1 = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEEBBEEBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBMWWWBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BB  BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const sleep = [
  "                ",
  " ZZZ            ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBBBBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BB  BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const sick = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBXXBBXXBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBWBBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BB  BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const happy = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBEEEEEEEEBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBBBBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "    BB    BB    ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

/** Depois de bronca: semblante fechado + tremer um pouco nas pernas. */
const scold1 = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEWWEEWBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBMWWMWBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BB  BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const scold2 = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEWWEEWBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBMWWMWBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "    BBB  BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const poop = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEEBBEEBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBBBBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BBBBBB     ",
  "       WW       ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const walk1 = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEEBBEEBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBBBBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "     BB BB      ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

const walk2 = [
  "                ",
  "                ",
  "      BBBB      ",
  "    BBBBBBBB    ",
  "   BBBBBBBBBB   ",
  "  BBBEEBBEEBBB  ",
  "  BBBBBBBBBBBB  ",
  "  BBBBBBBBBBBB  ",
  "   BBBBBBBBBB   ",
  "    BBBBBBBB    ",
  "      BB BB     ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

/**
 * Ovo oval: A = rebordo fechado (esq. e dir.), B = casca, W = brilho.
 * egg2 só desloca o W — para eclosão; idle = um frame + CSS no Pet.
 */
const egg = [
  "                ",
  "                ",
  "     ABBBA      ",
  "    ABBBBBA     ",
  "   ABBBBBBBA    ",
  "  ABBBBBBBBBA   ",
  " ABBBBBBBBBBBA  ",
  " ABBBBWBBBBBBA  ",
  " ABBBBBBBBBBBA  ",
  "  ABBBBBBBBBA   ",
  "   ABBBBBBBA    ",
  "    ABBBBBA     ",
  "     ABBBA      ",
  "                ",
  "                ",
  "                ",
];

/** Brilho noutra coluna — forma idêntica ao egg. */
const egg2 = [
  "                ",
  "                ",
  "     ABBBA      ",
  "    ABBBBBA     ",
  "   ABBBBBBBA    ",
  "  ABBBBBBBBBA   ",
  " ABBBBBBBBBBBA  ",
  " ABBBBBWBBBBBA  ",
  " ABBBBBBBBBBBA  ",
  "  ABBBBBBBBBA   ",
  "   ABBBBBBBA    ",
  "    ABBBBBA     ",
  "     ABBBA      ",
  "                ",
  "                ",
  "                ",
];

const dead = [
  "                ",
  "      WWW       ",
  "     WWWWW      ",
  "    WWEEEEEWW   ",
  "   WWWWEEEEWW   ",
  "   WWWWBBBWWW   ",
  "    WWWBBWWW    ",
  "     WWWWW      ",
  "      WWW       ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
];

import type { PetAnimationState } from "@/types/pet";

export const framesFor: Record<
  PetAnimationState,
  readonly (readonly string[])[]
> = {
  idle: [idle, idle2],
  eating: [eat1, idle2, eat1, idle],
  walking: [walk1, walk2, walk1, walk2],
  sleeping: [sleep, sleep],
  happy: [happy, idle],
  sad: [idle, idle2],
  scolded: [scold1, scold2],
  sick: [sick, sick],
  pooping: [poop, poop, idle],
  death: [dead, dead, dead],
  hatching: [egg, egg2, idle, idle2],
};
